apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqlset
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 2
  template:
    metadata: 
      labels:
        app: mysql
    spec: 
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-store
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-password
                key: password

  volumeClaimTemplates:
  - metadata:
      name: mysql-store
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: "database"
      resources:
        requests:
          storage: 5Gi

